# fly.toml app configuration file generated for wabelzapi on 2024-12-02T19:51:28+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wabelzapi'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 3
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
http_checks = [
  { path = "/api/info/items", interval = "10s", timeout = "2s" }
]